name: Mineral Vein
load: startup
main: mort.mineralvein.MineralVein
version: 1.4.2
commands:
    mineralvein:
        description: Apply MineralVein populator on exisiting world. (Width corresponds to x)
        usage: \<command> apply worldname [x] [z] [width] [height]
