default:
    -
        block: GOLD_ORE
        # block, that represents this ore. Use name, block ID, or XX-YY for blockID and data

        #seed: 35434
        # used for random generator, pick random different number for each vein (random but deterministic by default)

        density: 0.3
        # ore chance multiplicator, default 1

        densityBonus: -0.5
        # density modification. Random number is between -1 and 1, this is applied and result is ore spawn chance (negative is zero chance), default 0
        # e.g. 0.0 will result in 50% of columns covered in ore, -0.5 25%, -0.9 5%, -1 0%

        thickness: 4
        # maximal vertical span from vein center, default 5

        heightAvg: 25
        # average height this vein spawn at, default 32

        heightVar: 20
        # maximal random difference from heightAvg, default 20

        heightRel: false
        # if true, result of heightAvg and heightVar calculation will be instead 
        # treated as "relative" to maxHeight in that area (you should use floats for heightAvg/Car)
        # defaults to false

        heightLength: 80
        # distance in blocks between height slope change, default 80
        # larger = larger veins horizontally

        densLength: 80
        # distance in blocks between density slope change, dafult 80
        # larger = more evenly dense veins

        #biomes: [forest,swamp]
        # this vein will manifest in given biomes. default: all biomes
        # biomes are (not all used by world gen): RAINFOREST, SWAMPLAND, SEASONAL_FOREST, FOREST, SAVANNA, SHRUBLAND, TAIGA, DESERT, PLAINS, ICE_DESERT, TUNDRA, HELL, SKY, OCEAN, RIVER, EXTREME_HILLS;;

        mode: replace
        # "add" will cause all already placed ore to remain, and this vein only to add new ores.
        # any other value will cause the old ore to be removed

        #exclude_biomes: [swampland]
        # same as biomes setting, this time sets the biomes that are specifically excluded for this vein. Takes precedence over "biomes"
        
    -
        block: IRON_ORE
        density: 0.4
        thickness: 5
        densityBonus: -0.4
        heightAvg: 32
        heightVar: 30
        heightLength: 80
        densLength: 80
        mode: replace
    -
        block: REDSTONE_ORE
        density: 0.7
        thickness: 3
        densityBonus: -0.5
        heightAvg: 10
        heightVar: 10
        heightLength: 10
        densLength: 30
        mode: replace
    -
        block: DIAMOND_ORE
        density: 0.5
        thickness: 3
        densityBonus: -0.6
        heightAvg: 10
        heightVar: 10
        heightLength: 10
        densLength: 40
        mode: replace
    -
        block: LAPIS_ORE
        density: 0.6
        thickness: 4
        densityBonus: -0.6
        heightAvg: 10
        heightVar: 10
        heightLength: 10
        densLength: 40
        mode: replace
    -
        block: COAL_ORE
        density: 0.2
        thickness: 8
        densityBonus: -0.1
        heightAvg: 40
        heightVar: 40
        heightLength: 80
        densLength: 80
        mode: replace