name: MineralVein
load: startup
main: mort.mineralvein.MineralVein
version: 0.1-SNAPSHOT
commands:
    mineralvein:
        description: |
            Apply MineralVein populator on exisiting world.
            X and z chunk coordinates control the center of chunk crawl, is spawnpoint chunk by default.
            Use 'stop' instead of 'apply' to cancel a currently in progress apply.
        usage: /<command> apply worldname [x] [z] [chunks processed per tick]
